---
- name: Ensure user exists
  ansible.builtin.user:
    name: qcuser
    state: present
    shell: /bin/bash
    group: users
  register: qcuser
  become: true

- name: Setup Python virtual environment
  ansible.builtin.pip:
    name: pip>=23.1.2
    state: present
    virtualenv: "{{ qcuser.home }}/qcuser-venv"
    virtualenv_site_packages: true
    virtualenv_command: /opt/miniconda3/bin/python3.11 -m venv
  become: true
  become_user: qcuser

- name: Install ipykernel and poetry
  ansible.builtin.pip:
    name:
      - ipykernel
      - poetry
    state: present
    virtualenv: "{{ qcuser.home }}/qcuser-venv"
  become: true
  become_user: qcuser

- name: Setup pykernel config
  ansible.builtin.command:
    cmd: >-
      "{{ qcuser.home }}/qcuser-venv/bin/python"
      -m ipykernel install
      --user
      "--name={{ qcuser.name }}"
      --display-name="Python (QC users)"
    creates: "{{ qcuser.home }}/.local/share/jupyter/kernels/{{ qcuser.name }}/kernel.json"
  become: true
  become_user: qcuser

# - name: Memorize Pypi password
#   ansible.builtin.copy:
#     src: netrc
#     dest: "{{ qcuser.home }}/.netrc"
#     mode: "0600"
#   become: true
#   become_user: qcuser

# Assuming the ssh key is already registered on Github, clone the repo
- name: Clone pleno-droid.git
  ansible.builtin.git:
    repo: git@github.com:Pleno-Inc/pleno-droid.git
    version: 3d65054a997cb70037caaf6893b97f05ae29c01b
    dest: "{{ qcuser.home }}/pleno-droid"
  become: true
  become_user: qcuser

# Note(Antony): Use Ansible community library for Poetry
- name: Resolve dependencies with Poetry
  ansible.builtin.command:
    chdir: "{{ qcuser.home }}/pleno-droid"
    cmd: "{{ qcuser.home }}/qcuser-venv/bin/poetry install"
  changed_when: false
  become: true
  become_user: qcuser

- name: Install pleno-droid
  ansible.builtin.pip:
    chdir: "{{ qcuser.home }}/pleno-droid"
    name: .
    state: present
    extra_args: --extra-index-url https://pypi.plenoinc.com
    virtualenv: "{{ qcuser.home }}/qcuser-venv"
  changed_when: false
  become: true
  become_user: qcuser

# Download the OpenHTF framework source code, but don't install it. We don't use
# the framework's web frontend and the test history serialization with protobuf.
- name: Clone google/openhtf
  ansible.builtin.git:
    repo: https://github.com/google/openhtf.git
    version: 865512ad0eb8b5bf9a870f1ca30a92899593e63a
    dest: "{{ qcuser.home }}/openhtf"
  become: true
  become_user: qcuser

# Provides visualization code
- name: Clone pleno-qc.git
  ansible.builtin.git:
    repo: git@github.com:Pleno-Inc/pleno-qc.git
    version: feat/homogeneity-cleanup
    dest: "{{ qcuser.home }}/pleno-qc"
  become: true
  become_user: qcuser

- name: Install pleno-qc
  ansible.builtin.pip:
    chdir: "{{ qcuser.home }}/pleno-qc"
    name:
      - opencv-python
      - scikit-image
      - parsimonious
      - matplotlib
      - .
      - pleno-common==6.16.0
      # OpenHTF minimal dependencies
      - colorama>=0.3.9
      - contextlib2>=0.5.1
      - inflection
    state: present
    extra_args: --extra-index-url https://pypi.plenoinc.com
    virtualenv: "{{ qcuser.home }}/qcuser-venv"
  become: true
  become_user: qcuser
