---
- name: Install NTP server
  ansible.builtin.apt:
    name: chrony
    state: present
  become: true

- name: Configure NTP server
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    mode: "0644"
  notify: Restart NTP
  become: true
